print('Welcome to the python phq9 test')
print('Instructions:')
print('Answer every question honestly with a rating of 1-4 based on this scale')
print('1 - not at all')
print('2 - Several days')
print('3 - more than half the days')
print('4 - nearly every day')
print('IMPORTANT NOTES:')
print('This is not a subsitute for medical advice or a diagnostic tool. It is for informational purposes only')
print('If you think you may be in crisis, contact an organization listed on http://bit.ly/2h713hM or your local emergency services.')
print('--START--')
print('Over the last 2 weeks, how often have you been bothered by any of the following problems?')
a1 = raw_input('Little interest or pleasure in doing things :')
a2 = raw_input('Feeling down, depressed, or hopeless :')
a3 = raw_input('Trouble falling/staying asleep, sleeping too much  :')
a4 = raw_input('Feeling tired or having little energy :')
a5 = raw_input('Poor appetite or overeating : ')
a6 = raw_input('Feeling bad about yourself or that you are a failure or have let yourself or your family down  :')
a7 = raw_input('Trouble concentrating on things, such as reading the newspaper or watching television.  :')
a8 = raw_input(' Moving or speaking so slowly that other people could have noticed. Or the opposite; being so fidgety or restless that you have been moving around a lot more than usual. :')
a9 = raw_input('Thoughts that you would be better off dead or of hurting yourself in some way.  :')
score = int(a1) + int(a2) + int(a3) + int(a4) + int(a5) + int(a6) + int(a7) + int(a8) + int(a9)
print('Score: ' + str(score) + '/36')
raw_input('press enter to close')

